### ISSUE TITLE
Sidebar shows title instead of favicons

### ISSUE THREAD

**Issue by 119z** [Redundakitties/colorful-minimalist#7]
So, maybe I misunderstood something in the instructions, but I can't seem to make Sidebery show the favicon when it's 'hidden'. Right now, it just shows a bit of the tab title.

![image](https://user-images.githubusercontent.com/55221203/234754530-8452ac1d-d30f-4730-9cd8-f107644ce52b.png)

Is there anything I can do to change this? I'm using Firefox stable (112.02) and sideberyv5 beta. I copied the userchrome, changed SideberyMods to sideberyModsLEFT, and copied the sideberyv5tweaks in the extension's custom editor. I wanted to try moving the sidebar to the right but I can't find the setting, if there's any, and Google didn't help much.

I was also wondering if there's any way to move the contents of the screen/tab to right instead of having the sidebar covering part of the screen?

Thank you in advance!

**Comment by Redundakitties** [comment]
if you want the sidebar to be on the right you should copy and paste the [sideberyMods](https://github.com/Redundakitties/colorful-minimalist/blob/main/hacks/sideberyMods.css) file (no LEFT). This will also move the contents of the tab a bit as well so that it doesn't cover any content. 

Edit 1:
— wait you changed from SideberyMods → SideberymodsLEFT? Was it showing on the left even with sideberymods? I'm not sure why it would do that.

Edit 2:
Wait okay when you say "sidebar" do you mean the favicon section? as in do you want it to look like this:

https://user-images.githubusercontent.com/38409600/234759760-fe0a901c-5d90-4ecd-82c7-b7561f996f69.mp4

**Comment by 119z** [comment]
Yes, that's right, that's how I want it to look like! And even with sideberyMods, the sidebar remains on the left, so I'm not sure what's happening. I'm currently on Windows 11, in case that matters.
![image](https://user-images.githubusercontent.com/55221203/234911559-2e0fe3fe-87c4-4bb0-91a8-5cd15ce974b7.png)

I've already restarted multiple times after changing it.

**Comment by Redundakitties** [comment]
Ohhh oki. All you need to do is go into sidebery settings and change "pinned tabs" to be globally right. That should fix it!

**Comment by Redundakitties** [comment]
There's probably a way to change the collapsed panel so it's not covering the contents I'll have to look into it.

**Comment by 119z** [comment]
I think I funked something up when I was copying the codes, I redid the whole thing and managed to get it to move to the right but it still looks kinda wonky with the tree style tabs

![image](https://user-images.githubusercontent.com/55221203/234916256-43b07b6e-1c1e-4ac4-a1c1-a241d2e15228.png)

If I move it back to the left, it also looks like that even after changing the sidebery config. I already had the pinned tabs with the right setting when I first tried it, so I'm not sure why it didn't work then lol

![image](https://user-images.githubusercontent.com/55221203/234917088-2a09fe01-9a24-4adb-a193-7c5436fa45ae.png)

At least it seems like part of the screen content isn't getting covered anymore, and I also don't particularly care for the tree tabs style, so I don't mind turning it off.

Thank you anyway for your fast responses!

**Comment by Redundakitties** [comment]
Before you leave (just to try), test out this code: https://www.reddit.com/r/FirefoxCSS/comments/z8k0a5/-/j1pghk5

This should make it so when the sidebar is collapsed all the tabs should unindent. (Fixing the wonkyness). But when you hover over the sidebar they should reindent. I haven't tested this out for myself otherwise I'd take a video but I'll look into it soon. 

Oh also, np about the quick replies. Thank you so much for using my css! 

Also also if you're done with this whole thing I totally get it. Feel free to close this comment. I wish you luck on your userChrome adventures!

**Comment by 119z** [comment]
Just tried it and it worked great. It actually looks really neat when you slide the tabs open heh.

https://user-images.githubusercontent.com/55221203/235015087-d085d61d-d031-41e6-abeb-ac5341421559.mp4

One thing I just noticed is that when I open a new tab, the toolbar shifts down a bit. I thought it was because I mixed in some code from sidefox to have a oneliner display, but I just noticed it happening now even if I only have your css installed. If you look over to the first tab I have open you can see it shifts down a bit when I switch to a new tab. Not particularly bothersome, but something I thought you'd like to know.

https://user-images.githubusercontent.com/55221203/235016211-9d426096-6ac7-4b18-955c-20f5cf307462.mp4

![image](https://user-images.githubusercontent.com/55221203/235016428-a85ae386-076c-47e4-95ea-0559ab0203a9.png)

**Comment by Redundakitties** [comment]
Hmm I never see that behavior. Are you sure it's my css doing that? That's really weird

**Comment by 119z** [comment]
I refreshed FF, installed your css again and I don't see the issue anymore 😨 I don't know what was going on... But at least I solved it! Thank you for all your help, you've been incredibly responsive:) I'll close the issue now.
